import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  container: { padding: "20px", width: "100%", color: "#eee" },
  layout: {
    display: "grid",
    gridTemplateColumns: "1fr 2fr",
    gap: "30px",
    alignItems: "flex-start",
  },
  form: {
    background: "#1a1a1a",
    border: "1px solid #333",
    borderRadius: "10px",
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  label: { fontSize: "0.85rem", color: "#888" },
  input: {
    padding: "10px",
    background: "#222",
    border: "1px solid #444",
    color: "#fff",
    borderRadius: "6px",
    fontSize: "0.95rem",
  },
  textarea: {
    padding: "10px",
    background: "#222",
    border: "1px solid #444",
    color: "#fff",
    borderRadius: "6px",
    fontSize: "0.95rem",
    minHeight: "100px",
    resize: "vertical",
  },
  button: {
    padding: "10px",
    marginTop: "6px",
    background: "#4facf7",
    color: "#000",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "0.95rem",
  },
  list: { display: "flex", flexDirection: "column", gap: "12px" },
  card: {
    background: "#1a1a1a",
    border: "1px solid #333",
    borderRadius: "8px",
    padding: "16px",
  },
  dateBadge: {
    fontSize: "0.75rem",
    color: "#666",
    whiteSpace: "nowrap",
  },
  error: {
    color: "#ff6b6b",
    padding: "10px",
    background: "rgba(255,0,0,0.1)",
    borderRadius: "4px",
    marginBottom: "16px",
  },
  deleteBtn: {
    background: "transparent",
    border: "1px solid #555",
    color: "#ff6b6b",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "0.75rem",
    padding: "2px 7px",
    lineHeight: "1.5",
  },
};
