import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  container: { padding: "20px", width: "100%", color: "#eee" },
  input: {
    padding: "10px",
    marginRight: "10px",
    width: "320px",
    background: "#222",
    border: "1px solid #444",
    color: "#fff",
    borderRadius: "4px",
  },
  button: {
    padding: "10px 20px",
    cursor: "pointer",
    background: "#333",
    color: "#fff",
    border: "1px solid #555",
    borderRadius: "4px",
  },
  buttonOutline: {
    padding: "8px 16px",
    cursor: "pointer",
    background: "transparent",
    color: "#fff",
    border: "1px solid #777",
    borderRadius: "4px",
    transition: "0.2s",
  },
  clearButton: {
    padding: "6px 12px",
    cursor: "pointer",
    background: "transparent",
    color: "#ff6b6b",
    border: "1px solid #ff6b6b",
    borderRadius: "4px",
    fontSize: "0.85rem",
  },
  error: {
    color: "#ff6b6b",
    marginBottom: "20px",
    padding: "10px",
    background: "rgba(255, 0, 0, 0.1)",
    borderRadius: "4px",
  },
  resultCard: {
    border: "1px solid #444",
    padding: "20px",
    marginBottom: "30px",
    borderRadius: "8px",
    background: "#1a1a1a",
  },
  table: { width: "100%", textAlign: "left", borderCollapse: "collapse" },
  tableHeaderRow: { borderBottom: "2px solid #555" },
  tableRow: { borderBottom: "1px solid #333" },
  th: { padding: "12px 8px", color: "#bbb" },
  td: { padding: "12px 8px" },
  quickSelectContainer: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "8px",
    marginBottom: "25px",
  },
  quickSelectButton: {
    padding: "4px 12px",
    fontSize: "0.85rem",
    background: "transparent",
    color: "#aaa",
    border: "1px solid #444",
    borderRadius: "16px",
    cursor: "pointer",
  },
  gridContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: "20px",
  },
  gridCard: {
    border: "1px solid #444",
    padding: "15px",
    borderRadius: "8px",
    background: "#1e1e1e",
    display: "flex",
    flexDirection: "column",
  },
};
